Abatap.Web/Models/AccountViewModels.cs
using System.ComponentModel.DataAnnotations;

namespace Abatap.Web.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

Abatap.Web/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Abatap.Web.Models
{
    public class Customer
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PersonalId { get; set; }
    }
}

Abatap.Web/Models/CustomerListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Abatap.Web.Models
{
    public class CustomerListModel
    {
        public DateTime GeneratedDate { get; set; }
        public List<Customer> CustomerList { get; set; }
    }
}

Abatap.Web/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace Abatap.Web.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection")
        {
        }
    }
}

Abatap.Web/Controllers/CustomerListController.cs
using Abatap.Services.Contracts.Model;
using Abatap.Web.Models;
using Abatap.Web.ServiceProxies.Customer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Abatap.Web.Controllers
{
    public class CustomerListController : Controller
    {
        public ActionResult Index()
        {
            CustomerServiceProxy proxy = new CustomerServiceProxy();
            IEnumerable<CustomerDto> customers = proxy.GetAllCustomers();

            CustomerListModel model = new CustomerListModel();
            model.CustomerList = new List<Customer>();
            foreach (var item in customers)
            {
                model.CustomerList.Add(new Customer() { Name = item.Name, Surname = item.Surname });
            }
            model.GeneratedDate = DateTime.Now;
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Customer c)
        {
            CustomerServiceProxy proxy = new CustomerServiceProxy();
            CustomerDto customer = new CustomerDto() { Name = c.Name, Surname = c.Surname, PersonalId = c.PersonalId };
            proxy.SaveCustomer(customer);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult AddBackbone()
        {
            return View();
        }


        [HttpPost]
        public JsonResult AddBackbone(Customer c)
        {
            CustomerServiceProxy proxy = new CustomerServiceProxy();
            CustomerDto customer = new CustomerDto() { Name = c.Name, Surname = c.Surname, PersonalId = c.PersonalId };
            proxy.SaveCustomer(customer);
            return  Json(new HttpResponseMessage(HttpStatusCode.OK));
        }

    }
}

Abatap.Web/Views/CustomerList/Add.cshtml
@model Abatap.Web.Models.Customer

@{
    ViewBag.Title = "Nowy klient (MVC)";
}

<h2>Nowy klient</h2>
@using (Html.BeginForm())
{
    <p>Imie: @Html.EditorFor(x => x.Name)</p>
    <p>Nazwisko: @Html.EditorFor(x => x.Surname)</p>
    <p>Pesel: @Html.EditorFor(x=>x.PersonalId)</p>
    <input type="submit" value="Dodaj">
}

Abatap.Web/Views/CustomerList/AddBackbone.cshtml
@{
    ViewBag.Title = "AddBackbone";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Nowy klient (Backbone)";
}

<h2>Nowy klient</h2>
<div id="Content"></div>


<script type="text/template" id="addTemplate">
    <p><label>Imie: </label><input type="text" id="addFirstName" /></p>
    <p><label>Nazwisko: </label><input type="text" id="addLastName" /></p>
    <p><label>Pesel: </label><input type="text" id="addPesel" /></p>
    <p><input type="button" id="add_button" value="Dodaj" /></p>
</script>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/underscore.js"></script>
<script src="~/Scripts/backbone.js"></script>


<script src="~/Scripts/AddBackbone/Add.js"></script>

Abatap.Web/Views/CustomerList/Index.cshtml
@using Abatap.Web.Models
@model CustomerListModel

@{
    ViewBag.Title = "Lista klientów";
}

<h2>Lista klientów</h2>

<table>
    @foreach (Customer item in Model.CustomerList)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Surname</td>
        </tr>
    }
</table>

<p> </p>
<p><a href="/CustomerList/Add">Dodaj klienta (MVC)</a></p>
<p>@Html.ActionLink("Dodaj klienta (Backbone)", "AddBackbone", "CustomerList")</p>
<h6>Data wygenerowania: @Model.GeneratedDate.ToShortDateString()</h6>

Abatap.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Abatap</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ABATAP", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Lista klientów", "Index", "CustomerList")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>